replicaCount: 2

image:
  repository: 741448928302.dkr.ecr.eu-west-1.amazonaws.com/car-trawler-interview/nodejs-app
  tag: "1"
  pullPolicy: IfNotPresent
  pullSecrets:
    - name: ecr

service:
  name: nodejs-svc
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: ad4ee035f8df843d79165974acde1c7b-1978458333.eu-west-1.elb.amazonaws.com
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 300m
    memory: 500Mi
  limits:
    cpu: 1
    memory: 1Gi

probes:
  liveness:
    path: /helm
    port: 8000
    initialDelaySeconds: 40
    periodSeconds: 3
    timeoutSeconds: 10
    failureThreshold: 3
  readiness:
    path: /
    port: 8000
    initialDelaySeconds: 10
    periodSeconds: 3
    timeoutSeconds: 10
    failureThreshold: 3
